#include <objects/damage_new.h>

/* ---------- definitions */

TAG_ENUM(
	damage_reporting_type_enum,
	k_number_of_damage_reporting_types)
{
	{ "guardians_unknown", _damage_reporting_type_guardians_unknown },
	{ "guardians", _damage_reporting_type_guardians },
	{ "guardians_scripting", _damage_reporting_type_guardians_scripting },
	{ "suicide", _damage_reporting_type_suicide },
	{ "magnum", _damage_reporting_type_magnum },
	{ "assault_rifle", _damage_reporting_type_assault_rifle },
	{ "dmr", _damage_reporting_type_dmr },
	{ "shotgun", _damage_reporting_type_shotgun },
	{ "sniper_rifle", _damage_reporting_type_sniper_rifle },
	{ "rocket_launcher", _damage_reporting_type_rocket_launcher },
	{ "spartan_laser", _damage_reporting_type_spartan_laser },
	{ "frag_grenade", _damage_reporting_type_frag_grenade },
	{ "grenade_launcher", _damage_reporting_type_grenade_launcher },
	{ "plasma_pistol", _damage_reporting_type_plasma_pistol },
	{ "needler", _damage_reporting_type_needler },
	{ "plasma_rifle", _damage_reporting_type_plasma_rifle },
	{ "plasma_repeater", _damage_reporting_type_plasma_repeater },
	{ "needle_rifle", _damage_reporting_type_needle_rifle },
	{ "spiker", _damage_reporting_type_spiker },
	{ "plasma_launcher", _damage_reporting_type_plasma_launcher },
	{ "gravity_hammer", _damage_reporting_type_gravity_hammer },
	{ "energy_sushort", _damage_reporting_type_energy_sushort },
	{ "plasma_grenade", _damage_reporting_type_plasma_grenade },
	{ "concussion_rifle", _damage_reporting_type_concussion_rifle },
	{ "ghost", _damage_reporting_type_ghost },
	{ "revenant", _damage_reporting_type_revenant },
	{ "revenant_gunner", _damage_reporting_type_revenant_gunner },
	{ "wraith", _damage_reporting_type_wraith },
	{ "wraith_turret", _damage_reporting_type_wraith_turret },
	{ "banshee", _damage_reporting_type_banshee },
	{ "banshee_bomb", _damage_reporting_type_banshee_bomb },
	{ "seraph", _damage_reporting_type_seraph },
	{ "mongoose", _damage_reporting_type_mongoose },
	{ "warthog", _damage_reporting_type_warthog },
	{ "warthog_chaingun", _damage_reporting_type_warthog_chaingun },
	{ "warthog_gauss", _damage_reporting_type_warthog_gauss },
	{ "warthog_rocket", _damage_reporting_type_warthog_rocket },
	{ "scorpion", _damage_reporting_type_scorpion },
	{ "scorpion_turret", _damage_reporting_type_scorpion_turret },
	{ "falcon", _damage_reporting_type_falcon },
	{ "falcon_gunner", _damage_reporting_type_falcon_gunner },
	{ "falling", _damage_reporting_type_falling },
	{ "generic_collision", _damage_reporting_type_generic_collision },
	{ "generic_melee", _damage_reporting_type_generic_melee },
	{ "generic_explosion", _damage_reporting_type_generic_explosion },
	{ "birthday_explosion", _damage_reporting_type_birthday_explosion },
	{ "flag", _damage_reporting_type_flag },
	{ "bomb", _damage_reporting_type_bomb },
	{ "bomb_explosion", _damage_reporting_type_bomb_explosion },
	{ "ball", _damage_reporting_type_ball },
	{ "teleporter", _damage_reporting_type_teleporter },
	{ "shifted_blame", _damage_reporting_type_shifted_blame },
	{ "armor_lock", _damage_reporting_type_armor_lock },
	{ "target_locator", _damage_reporting_type_target_locator },
	{ "human_turret", _damage_reporting_type_human_turret },
	{ "plasma_cannon", _damage_reporting_type_plasma_cannon },
	{ "plasma_mortar", _damage_reporting_type_plasma_mortar },
	{ "plasma_turret", _damage_reporting_type_plasma_turret },
	{ "shade_turret", _damage_reporting_type_shade_turret },
	{ "sabre", _damage_reporting_type_sabre },
	{ "focus_rifle", _damage_reporting_type_focus_rifle },
	{ "fuel_rod", _damage_reporting_type_fuel_rod },
	{ "missile_pod", _damage_reporting_type_missile_pod },
	{ "tank", _damage_reporting_type_tank },
	{ "hornet", _damage_reporting_type_hornet },
};
