#include <scenario/scenario.h>

/* ---------- definitions */

TAG_ARRAY(
	_field_long_integer,
	scenario_object_identifiers_array,
	32);

TAG_GROUP(
	scenario_group,
	k_scenario_group_tag,
	sizeof(s_scenario))
{
	{ _field_short_enum, "scenario_type", nullptr },
	{ _field_word_flags, "flags", nullptr },
	{ _field_long_integer, "unknown1" },
	{ _field_long_integer, "campaign_id" },
	{ _field_long_integer, "map_id" },
	{ _field_string_id, "scenario_name" },
	{ _field_short_integer, "campaign_level_index" },
	{ _field_short_integer, "unknown2" },
	{ _field_long_integer, "unknown3" },
	{ _field_angle, "local_north" },
	{ _field_real, "unknown4" },
	{ _field_real, "unknown5" },
	{ _field_real, "unknown6" },
	{ _field_real, "unknown7" },
	{ _field_real, "unknown8" },
	{ _field_real, "sandbox_budget" },
	{ _field_string_id, "default_vehicle_filter" },
	{ _field_tag_reference, "performance_throttle_profile", nullptr },
	{ _field_block, "structure_bsps", nullptr },
	{ _field_block, "structure_designs", nullptr },
	{ _field_tag_reference, "structure_seams", nullptr },
	{ _field_tag_reference, "local_structure_seams", nullptr },
	{ _field_block, "skies", nullptr },
	{ _field_block, "zone_set_pvs", nullptr },
	{ _field_block, "zone_set_audibility", nullptr },
	{ _field_block, "zone_sets", nullptr },
	{ _field_block, "unknown9", nullptr },
	{ _field_block, "unknown10", nullptr },
	{ _field_block, "unknown11", nullptr },
	{ _field_block, "unknown12", nullptr },
	{ _field_data, "editor_scenario_data" },
	{ _field_block, "unknown13", nullptr },
	{ _field_block, "object_names", nullptr },
	{ _field_block, "scenery", nullptr },
	{ _field_block, "scenery_palette", nullptr },
	{ _field_block, "bipeds", nullptr },
	{ _field_block, "biped_palette", nullptr },
	{ _field_block, "vehicles", nullptr },
	{ _field_block, "vehicle_palette", nullptr },
	{ _field_block, "equipment", nullptr },
	{ _field_block, "equipment_palette", nullptr },
	{ _field_block, "weapons", nullptr },
	{ _field_block, "weapon_palette", nullptr },
	{ _field_block, "device_groups", nullptr },
	{ _field_block, "machines", nullptr },
	{ _field_block, "machine_palette", nullptr },
	{ _field_block, "terminals", nullptr },
	{ _field_block, "terminal_palette", nullptr },
	{ _field_block, "controls", nullptr },
	{ _field_block, "control_palette", nullptr },
	{ _field_block, "sound_scenery", nullptr },
	{ _field_block, "sound_scenery_palette", nullptr },
	{ _field_block, "giants", nullptr },
	{ _field_block, "giant_palette", nullptr },
	{ _field_block, "effect_scenery", nullptr },
	{ _field_block, "effect_scenery_palette", nullptr },
	{ _field_block, "light_volumes", nullptr },
	{ _field_block, "light_volume_palette", nullptr },
	{ _field_block, "sandbox_palette", nullptr },
	{ _field_block, "legacy_sandbox_info", nullptr },
	{ _field_tag_reference, "multiplayer_object_types", nullptr },
	{ _field_block, "unknown14", nullptr },
	{ _field_block, "soft_ceilings", nullptr },
	{ _field_block, "player_starting_profile", nullptr },
	{ _field_block, "player_starting_locations", nullptr },
	{ _field_block, "trigger_volumes", nullptr },
	{ _field_block, "unknown15", nullptr },
	{ _field_block, "unknown16", nullptr },
	{ _field_block, "unknown17", nullptr },
	{ _field_block, "unknown18", nullptr },
	{ _field_block, "unknown19", nullptr },
	{ _field_block, "zone_set_switch_trigger_volumes", nullptr },
	{ _field_block, "named_location_volumes", nullptr },
	{ _field_tag_reference, "airstrike_globals", nullptr },
	{ _field_block, "unknown20", nullptr },
	{ _field_block, "unknown21", nullptr },
	{ _field_block, "unknown22", nullptr },
	{ _field_block, "unknown23", nullptr },
	{ _field_block, "unknown24", nullptr },
	{ _field_block, "unknown25", nullptr },
	{ _field_block, "unknown26", nullptr },
	{ _field_block, "unknown27", nullptr },
	{ _field_block, "unknown28", nullptr },
	{ _field_block, "unknown29", nullptr },
	{ _field_block, "decals", nullptr },
	{ _field_block, "decal_palette", nullptr },
	{ _field_block, "unknown30", nullptr },
	{ _field_block, "unknown31", nullptr },
	{ _field_block, "squad_groups", nullptr },
	{ _field_block, "squads", nullptr },
	{ _field_block, "zones", nullptr },
	{ _field_block, "unknown32", nullptr },
	{ _field_block, "ai_cues", nullptr },
	{ _field_block, "unknown33", nullptr },
	{ _field_block, "unknown34", nullptr },
	{ _field_block, "unknown35", nullptr },
	{ _field_block, "character_palette", nullptr },
	{ _field_block, "unknown36", nullptr },
	{ _field_block, "ai_pathfinding_data", nullptr },
	{ _field_block, "unknown37", nullptr },
	{ _field_data, "script_strings" },
	{ _field_block, "scripts", nullptr },
	{ _field_block, "globals", nullptr },
	{ _field_block, "script_references", nullptr },
	{ _field_block, "unknown38", nullptr },
	{ _field_block, "scripting_data", nullptr },
	{ _field_block, "cutscene_flags", nullptr },
	{ _field_block, "cutscene_camera_points", nullptr },
	{ _field_block, "cutscene_titles", nullptr },
	{ _field_tag_reference, "custom_object_name_strings", nullptr },
	{ _field_tag_reference, "chapter_title_strings", nullptr },
	{ _field_block, "scenario_resources", nullptr },
	{ _field_block, "unit_seats_mapping", nullptr },
	{ _field_block, "kill_triggers", nullptr },
	{ _field_block, "safe_triggers", nullptr },
	{ _field_block, "mopp_triggers", nullptr },
	{ _field_block, "unknown39", nullptr },
	{ _field_block, "unknown40", nullptr },
	{ _field_block, "script_expressions", nullptr },
	{ _field_block, "unknown41", nullptr },
	{ _field_block, "unknown42", nullptr },
	{ _field_block, "background_sound_environment_palette", nullptr },
	{ _field_block, "fog", nullptr },
	{ _field_block, "camera_fx", nullptr },
	{ _field_block, "weather", nullptr },
	{ _field_block, "scenario_cluster_data", nullptr },
	{ _field_array, "object_identifiers", &scenario_object_identifiers_array },
	{ _field_block, "spawn_data", nullptr },
	{ _field_tag_reference, "sound_effects_collection", nullptr },
	{ _field_block, "crates", nullptr },
	{ _field_block, "crate_palette", nullptr },
	{ _field_block, "flock_palette", nullptr },
	{ _field_block, "flocks", nullptr },
	{ _field_tag_reference, "subtitle_strings", nullptr },
	{ _field_block, "unknown43", nullptr },
	{ _field_block, "creature_palette", nullptr },
	{ _field_block, "big_battle_creatures", nullptr },
	{ _field_block, "editor_folders", nullptr },
	{ _field_tag_reference, "territory_location_name_strings", nullptr },
	{ _field_long_integer, "unknown44" },
	{ _field_long_integer, "unknown45" },
	{ _field_block, "mission_dialogue", nullptr },
	{ _field_tag_reference, "objective_strings", nullptr },
	{ _field_tag_reference, "scenario_interpolator", nullptr },
	{ _field_block, "unknown46", nullptr },
	{ _field_tag_reference, "default_camera_fx", nullptr },
	{ _field_tag_reference, "default_screen_fx", nullptr },
	{ _field_tag_reference, "ambient_occlusion_profile", nullptr },
	{ _field_tag_reference, "sky_parameters", nullptr },
	{ _field_tag_reference, "fog_parameters", nullptr },
	{ _field_tag_reference, "global_lighting", nullptr },
	{ _field_tag_reference, "lightmap", nullptr },
	{ _field_tag_reference, "performance_throttles", nullptr },
	{ _field_block, "unknown47", nullptr },
	{ _field_block, "ai_objectives", nullptr },
	{ _field_block, "designer_zones", nullptr },
	{ _field_block, "unknown48", nullptr },
	{ _field_block, "unknown49", nullptr },
	{ _field_block, "particle_emitters", nullptr },
	{ _field_block, "unknown50", nullptr },
	{ _field_block, "cinematics", nullptr },
	{ _field_block, "cinematic_lights", nullptr },
	{ _field_block, "unknown51", nullptr },
	{ _field_block, "scenario_metagame", nullptr },
	{ _field_block, "unknown52", nullptr },
	{ _field_block, "unknown53", nullptr },
	{ _field_block, "unknown54", nullptr },
	{ _field_block, "unknown55", nullptr },
	{ _field_block, "unknown56", nullptr },
	{ _field_block, "vignettes", nullptr },
	{ _field_tag_reference, "map_location_globals", nullptr },
	{ _field_block, "unknown57", nullptr },
	{ _field_tag_reference, "mission_hud", nullptr },
	{ _field_tag_reference, "required_resources", nullptr },
	{ _field_tag_reference, "variant_globals", nullptr },
	{ _field_block, "compiled_data", nullptr },
	{ _field_terminator }
};
